version: "3.2"

services:
  wash_db:
    container_name: wash_postgresql
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER:  ${WASH_DB_USER:-wash_bonus}
      POSTGRES_PASSWORD: ${WASH_DB_PASS:-wash_bonus}
    volumes:
      - wash_bonus_postgresql:/var/lib/postgresql/data
    ports:
      - "8090:5432"

  wash_bonus_back:
    container_name: wash_bonus_backend
    restart: always
    ports:
      - ${WASH_BONUS_HTTP_PORT:-8070}:8080
    depends_on:
      - wash_db
      - wash_rabbit
    build:
      context: .
      dockerfile: ./wash_bonus.Dockerfile
    environment:
      LOG_LEVEL: "info"
      DB_USER: ${WASH_BONUS_DB_USER:-wash_bonus}
      DB_PASSWORD: ${WASH_BONUS_DB_PASS:-wash_bonus}

  wash_rabbit:
    container_name: wash_rabbit
    hostname: 'wash_rabbit'
    user: "rabbitmq"
    image: rabbitmq:3.11.8-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./environment/rabbit/definitions.json:/etc/rabbitmq/definitions.json
      - ./environment/rabbit/rabbit.conf:/etc/rabbitmq/rabbitmq.conf
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-logs:/var/log/rabbitmq

  postgres:
    image: postgres:14.5
    container_name: wash_sbp_postgresql
    environment:
      POSTGRES_USER: sbp_admin
      POSTGRES_PASSWORD: sbp_admin_password
      POSTGRES_DB: postgres
    volumes:
      - sbp_postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "54327:5432"

  sbp_client:
    build:
      context: ../sbp
      dockerfile: Dockerfile
    image: sbp_client
    container_name: sbp_client
    volumes:
      - .:/app
    ports:
      - "8080:8080"

volumes:
  rabbitmq-data:
    driver: local
  rabbitmq-logs:
    driver: local
  wash_bonus_postgresql:
    driver: local
  sbp_postgres_data:
    driver: local