version: "3.8"

services:
  db_wash_bonus:
    container_name: wash_bonus_postgresql
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: back
    ports:
      - 8090:5432

#  back:
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#      args:
#        GITHUB_USER: ${GITHUB_USER:?}
#        GITHUB_PASS: ${GITHUB_PASS:?}
#    ports:
#      - ${MSRV_PORT:-9091}:${MSRV_PORT:-9091}
#    depends_on:
#      - db_wash_bonus
#    environment:
#      MSRV_PORT: ${MSRV_PORT:-9091}
#      MSRV_RESET_DB: ${MSRV_RESET_DB:-false}
#      MSRV_DB_HOST: db
#      MSRV_DB_PORT: "5432"
#      MSRV_DB_USER: postgres
#      MSRV_DB_PASS: postgres
#      MSRV_DB_NAME: back
#      MSRV_CORS_ALLOWED_ORIGINS: ${MSRV_CORS_ALLOWED_ORIGINS:-http://localhost}
#      MSRV_DB_SSL_MODE_IS_REQUIRE: "false"
#      MSRV_MAILER_FROM: ${MSRV_MAILER_FROM}
#      MSRV_MAILER_FROM_NAME: ${MSRV_MAILER_FROM_NAME}
#      MSRV_MAILER_PASS: ${MSRV_MAILER_PASS}
#      FIREBASE_KEYFILE_PATH: ${FIREBASE_KEYFILE_PATH:-~/firebase_keyfile.json}
