version: "3.8"


services:
  db_wash_admin:
    container_name: wash_admin_postgresql
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER:  ${WASH_ADMIN_DB_USER:-wash_admin}
      POSTGRES_PASSWORD: ${WASH_ADMIN_DB_PASS:-wash_admin}
    ports:
      - "8091:5432"
  
  db_wash_bonus:
    container_name: wash_bonus_postgresql
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER: ${WASH_BONUS_DB_USER:-wash_bonus}
      POSTGRES_PASSWORD: ${WASH_BONUS_DB_PASS:-wash_bonus}
    ports:
      - "8090:5432"

  wash_bonus_back:
    container_name: wash_bonus_backend
    restart: always
    ports:
      - ${WASH_BONUS_HTTP_PORT:-8071}:8071
    depends_on:
      - db_wash_bonus
      - wash_rabbit
    build:
      context: .
      dockerfile: ./wash_bonus.Dockerfile
    environment:
      LOG_LEVEL: "info"
      DB_USER: ${WASH_BONUS_DB_USER:-wash_bonus}
      DB_PASSWORD: ${WASH_BONUS_DB_PASS:-wash_bonus}
  wash_admin_back:
    container_name: wash_admin_backend
    restart: always
    ports:
      - ${WASH_ADMIN_HTTP_PORT:-8070}:8070
    depends_on:
      - db_wash_bonus
      - wash_rabbit
    build:
      context: .
      dockerfile: ./wash_admin.Dockerfile
    environment:
      LOG_LEVEL: "info"
      DB_USER: ${WASH_ADMIN_DB_USER:-wash_admin}
      DB_PASSWORD:   ${WASH_ADMIN_DB_PASS:-wash_admin}

  wash_rabbit:
    container_name: wash_rabbit
    image: rabbitmq:3.11.6-management
    restart: always
    ports:
      - "5671:5671"
      - "15672:15672"
    volumes:
      - ./environment/certs/:/certs/
      - ./environment/rabbit/rabbit.conf:/etc/rabbitmq/rabbitmq.conf
      - ./environment/rabbit/data/:/var/lib/rabbitmq
      - ./environment/rabbit/log/:/var/log/rabbitmq
