version: "3.2"

services:
  wash_db:
    container_name: wash_postgresql
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER:  ${WASH_ADMIN_DB_USER:-wash_admin}
      POSTGRES_PASSWORD: ${WASH_ADMIN_DB_PASS:-wash_admin}
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./postgresql-data:/var/lib/postgresql/data
    ports:
      - "8090:5432"

  wash_bonus_back:
    container_name: wash_bonus_backend
    restart: always
    ports:
      - ${WASH_BONUS_HTTP_PORT:-8071}:8080
    depends_on:
      - wash_db
      - wash_rabbit
    build:
      context: .
      dockerfile: ./wash_bonus.Dockerfile
    environment:
      LOG_LEVEL: "info"
      DB_USER: ${WASH_BONUS_DB_USER:-wash_bonus}
      DB_PASSWORD: ${WASH_BONUS_DB_PASS:-wash_bonus}
  wash_admin_back:
    container_name: wash_admin_backend
    restart: always
    ports:
      - ${WASH_ADMIN_HTTP_PORT:-8070}:8080
    depends_on:
      - wash_db
      - wash_rabbit
    build:
      context: .
      dockerfile: ./wash_admin.Dockerfile
    environment:
      LOG_LEVEL: "info"
      DB_USER: ${WASH_ADMIN_DB_USER:-wash_admin}
      DB_PASSWORD:   ${WASH_ADMIN_DB_PASS:-wash_admin}

  wash_rabbit:
    container_name: wash_rabbit
    user: "rabbitmq"
    image: rabbitmq:3.11.8-management
    restart: always
    ports:
      - "5671:5671"
      - "15672:15672"
    volumes:
      - ./environment/certs/:/certs/
      - ./environment/rabbit/rabbit.conf:/etc/rabbitmq/rabbitmq.conf
      - ./environment/rabbit/definitions.json:/etc/rabbitmq/definitions.json
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
      
volumes:
  rabbitmq-data:
  rabbitmq-log:
