swagger: "2.0"
info:
  description: "microservice for the bonus system of self-service car washes"
  title: wash-bonus
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
securityDefinitions:
  authKey:
    description: Session token inside Authorization header.
    type: apiKey
    in: header
    name: Authorization
security:
  - authKey: [ ]
paths:
  /healthCheck:
    get:
      tags:
        - Standard
      security:
        - { }
      operationId: healthCheck
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              ok:
                type: boolean
  /profile/balance:
    get:
      tags:
        - user
      security:
        - authKey: [ ]
      operationId: getBalance
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              balance:
                type: integer
        404:
          description: Profile not exists
          schema:
            $ref: "#/definitions/error"
        500:
          description: Internal error
          schema:
            $ref: "#/definitions/error"
  /profile:
    get:
      tags:
        - user
      security:
        - authKey: [ ]
      operationId: getProfile
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/profile"
        404:
          description: Profile not exists
          schema:
            $ref: "#/definitions/error"
        500:
          description: Internal error
          schema:
            $ref: "#/definitions/error"

  /session/{UID}:
    get:
      tags:
        - session
      security:
        - authKey: [ ]
      operationId: getSession
      parameters:
        - name: UID
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/session"
        404:
          description: Profile not exists
          schema:
            $ref: "#/definitions/error"
        500:
          description: Internal error
          schema:
            $ref: "#/definitions/error"
    post:
      tags:
        - session
      security:
        - authKey: [ ]
      operationId: postSession
      parameters:
        - name: UID
          in: path
          type: string
          required: true
        - name: body
          in: body
          schema:
            $ref: "#/definitions/bonusCharge"
      responses:
        204:
          description: OK
        403:
          description: Forbidden
        404:
          description: Session not found
          schema:
            $ref: "#/definitions/error"
        500:
          description: Internal error
          schema:
            $ref: "#/definitions/error"

definitions:
  error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        description: Either same as HTTP Status Code OR >= 600.
        type: integer
        format: int32
      message:
        type: string

  profile:
    type: object
    description: "user profile"
    properties:
      id:
        type: string
      active:
        type: boolean
      balance:
        type: integer

  session:
    type: object
    description: "session"
    properties:
      washServer:
        $ref: "#/definitions/washServer"
      postID:
        type: integer
      postBalance:
        type: integer

  washServer:
    type: object
    description: "wash server info"
    properties:
      Name:
        type: string
      Description:
        type: string

  bonusCharge:
    type: object
    description: "bonus amount for use in session"
    properties:
      amount:
        type: integer