swagger: "2.0"
info:
  description: "microservice for the bonus system of self-service car washes"
  title: wash-admin
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
securityDefinitions:
  authKey:
    description: Session token inside Authorization header.
    type: apiKey
    in: header
    name: Authorization
security:
  - authKey: []
paths:
  /healthCheck:
    get:
      tags:
        - Standard
      security:
        - {}
      operationId: healthCheck
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              ok:
                type: boolean

  /wash-server:
    get:
      tags:
        - wash_servers
      security:
        - authKey: []
      operationId: get
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/WashServerGet"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/WashServer"
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/error"
        404:
          description: WashServer not exists
          schema:
            $ref: "#/definitions/error"
        500:
          description: Internal error
          schema:
            $ref: "#/definitions/error"

    put:
      tags:
        - wash_servers
      security:
        - authKey: []
      operationId: add
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/WashServerAdd"
      responses:
        200:
          description: Success creation
          schema:
            $ref: "#/definitions/WashServer"
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/error"
        500:
          description: Internal error
          schema:
            $ref: "#/definitions/error"

    patch:
      tags:
        - wash_servers
      security:
        - authKey: []
      operationId: update
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/WashServerUpdate"
      responses:
        204:
          description: Success update
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/error"
        404:
          description: WashServer not exists
          schema:
            $ref: "#/definitions/error"
        500:
          description: Internal error
          schema:
            $ref: "#/definitions/error"

    delete:
      tags:
        - wash_servers
      security:
        - authKey: []
      operationId: delete
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/WashServerDelete"
      responses:
        204:
          description: OK
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/error"
        404:
          description: WashServer not exists
          schema:
            $ref: "#/definitions/error"
        500:
          description: Internal error
          schema:
            $ref: "#/definitions/error"

  /wash-server/list:
    get:
      tags:
        - wash_servers
      security:
        - authKey: []
      operationId: list
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/Pagination"
      responses:
        200:
          description: OK
          schema:
            type: array
            items: 
              $ref: "#/definitions/WashServer"
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/error"
        404:
          description: WashServer not exists
          schema:
            $ref: "#/definitions/error"
        500:
          description: Internal error
          schema:
            $ref: "#/definitions/error"


definitions:
  error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        description: Either same as HTTP Status Code OR >= 600.
        type: integer
        format: int32
      message:
        type: string

  WashServer:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      service_key:
        type: string

  WashServerGet:
    type: object
    properties:
      id:
        type: string
    required:
      - id

  WashServerAdd:
    properties:
      name:
        type: string
      description:
        type: string
    required:
      - name

  WashServerUpdate:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string

  WashServerDelete:
    type: object
    properties:
      id:
        type: string
    required:
      - id

  Pagination:
    type: object
    properties: 
      limit:
        type: integer
        format: int64
        maximum: 100
      offset:
        type: integer
        format: int64
